# Welcome to Jekyll!
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: JXTech
subtitle: "Redefine Computing and Intelligence"
name: "JXTech"
description: "Advanced probability problems and detailed solutions"
url: "" # Leave blank for local development
baseurl: "" # Leave blank for your main GitHub Pages site

minimal_mistakes_skin: "air"

# Build settings
markdown: kramdown
mathjax: true
# Site Author
author:
  name: "JXTech"
  avatar: # Add path to avatar image if desired
  bio: "Providing detailed solutions to challenging probability problems"
  location: "Your Location"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TheAlphaJas"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-feed

# Defaults for posts
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      mathjax: true
      classes: wide

# Math support
head_scripts:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
repository: "jxtech-s/jxtech-s.github.io"

include:
  - problems
